### ISSUE TITLE
Exception when non-contiguous selection

### ISSUE THREAD

**Issue by insaner** [vondoRishi/AdvanceOfficeChart#4]
Hi, I was able to install on Apache OpenOffice 4.1.6, Fedora 27 32bit, Oracle JRE 1.8.0_191. 
(BTW, instructions somewhere should say it needs to be launched from the "Addons" menu. I was expecting it to be integrated into the native charts dialog, I thought the installation had silently failed).

It seems the addon throws an exception when the selection to be charted is non-contiguous. If the selection is contiguous, I can launch the addon, but if I add a non-contiguous column (or selection) and try to "Rescan" I get the exception again. If I try to launch the addon with the non-contiguous selection already selected, the addon fails to appear.

(Also, I cannot change the text in the textbox to edit the selection.)

I tried switching to Oracle JRE 1.7.0_75 but same issue. 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.advanceChart.util.OfficeUtil.getSelRangeText(OfficeUtil.java:43)
        at com.advanceChart.configureSteps.DataRange.configBean(DataRange.java:78)
        at com.advanceChart.configureSteps.DataRange.initialize(DataRange.java:73)
        at com.advanceChart.configureSteps.DataRange.<init>(DataRange.java:69)
        at com.advanceChart.AOCgui.initialize(AOCgui.java:157)
        at com.advanceChart.AOCgui.<init>(AOCgui.java:121)
        at com.advanceChart.RegisterAndService$1.run(RegisterAndService.java:122)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:699)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by vondoRishi** [comment]
Hi @insaner ,
Thank you for interest in "AdvanceOfficeChart" and reporting this bug. However, please send sample data to reproduce it.

**Comment by insaner** [comment]
Create a new spreadsheet, it can be empty. Select 5 cells in column B and 5 cells in column D. Try to launch the addon. Now deselect the cells from D, try to launch again. Now select the 5 cells in D again, and click "Rescan"

**Comment by vondoRishi** [comment]
Yes it is a bug but not severe, I will try to fix in future.

**Comment by insaner** [comment]
Thanks for your work on the addon, by the way!
